/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

class App {}


fun main(args: Array<String>) {
    val parser = ArgsParser(Schema(Flag("-l"), Flag("-p")))
    args
        .toSet()
        .let(parser::parse)
        .let(::println)
}
