/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

class App {}


fun main(args: Array<String>) {
    val parser = ArgsParser(Schema(setOf(Flag("-l", false), Flag("-p", false))))
    args
        .toSet()
        .let(parser::parse)
        .let(::println)
}
