/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

class App {}


fun main(args: Array<String>) {
    // Configure schema for app

    // Parse args using argparser
    args.forEach(::println)
}
