/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

import io.kotest.core.spec.style.WordSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe

class AppKoTest: WordSpec({
    "test should fail (kotest)" should {
        val classUnderTest = App()
        classUnderTest.greeting shouldBe null
    }
})
